// Autogenerated with Figma to Code - Tailwind CSS (JSX)
// Just for testing purposes
export const Header = () => (
  <div className="relative h-[68.92px] w-[1440.28px]">
    <div className="absolute left-0 top-0 h-[68.92px] w-[1440.28px] border-b border-zinc-500 bg-white bg-opacity-90" />
    <div className="absolute left-[74.46px] top-[17.37px] h-[34.18px]">
      <div className="absolute left-0 top-0 h-[34.18px] w-[34.18px] bg-zinc-500" />
      <div className="absolute left-[45.04px] top-[0.18px] font-['GothamSSm'] text-2xl font-bold leading-[33.60px] text-zinc-500">
        JOD
      </div>
    </div>
    <img
      className="absolute left-[1315.14px] top-[12.35px] h-[44.22px] w-[44.22px] rounded-full"
      src="https://via.placeholder.com/44x44"
      alt=""
    />
    <div className="absolute left-[700.07px] top-[16.58px] h-[37.76px] w-[123.34px] rounded-lg bg-zinc-500" />
    <div className="absolute left-[723.14px] top-[24.46px] inline-flex w-[543px] items-start justify-between">
      <div className="font-['GothamSSm'] text-base font-bold leading-snug text-white">Yksilöille</div>
      <div className="font-['GothamSSm'] text-base font-bold leading-snug text-black">Ohjaajille</div>
      <div className="font-['GothamSSm'] text-base font-bold leading-snug text-black">Kouluttajille</div>
      <div className="font-['GothamSSm'] text-base font-bold leading-snug text-black">Viranomaisille</div>
    </div>
  </div>
);
