import type { StoryObj } from '@storybook/react-vite';
import type { TitledMeta } from '../../utils';
import { AiInfoButton } from './AiInfoButton';

const meta = {
  title: 'Buttons/AiInfoButton',
  component: AiInfoButton,
  tags: ['autodocs'],
} satisfies TitledMeta<typeof AiInfoButton>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  parameters: {
    design: {
      type: 'figma',
      url: 'https://www.figma.com/design/6M2LrpSCcB0thlFDaQAI2J/cx_jod_client?node-id=10595-33227',
    },
    docs: {
      description: {
        story: 'This is a info button for marking AI generated content.',
      },
    },
  },
  args: {
    size: 24,
    tooltipContent: 'This content is generated by AI.',
  },
};

export const WithoutTooltip: Story = {
  parameters: {
    design: {
      type: 'figma',
      url: 'https://www.figma.com/design/6M2LrpSCcB0thlFDaQAI2J/cx_jod_client?node-id=10595-33227',
    },
    docs: {
      description: {
        story: 'This is just the AI icon without tooltip.',
      },
    },
  },
  args: {
    size: 24,
  },
};
